[package]
name = "metaboss"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
reqwest = "0.11.5"
serde = "1.0.130"
serde_json = "1.0.68"
solana-client = "1.8.0"
solana-program = "1.8.0"
solana-sdk = "1.8.0"
spl-token-metadata = "0.0.1"
structopt = "0.3.23"
thiserror = "1.0.30"

[features]
